2020-04-03 00:02:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:07:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:12:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:17:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:22:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:27:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:32:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:37:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:42:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:47:12 c.n.d.s.r.a.ConfigClusterResolver - Resolving eureka endpoints via configuration
2020-04-03 00:47:30 i.l.c.protocol.CommandHandler - [channel=0x545b54c7, /192.168.140.1:59354 -> /192.168.140.130:6379, chid=0x1] Unexpected exception during request: java.io.IOException: 远程主机强迫关闭了一个现有的连接。
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:148)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:628)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:563)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
2020-04-03 00:47:30 o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=orderTestGroupid] Group coordinator linux4:9092 (id: 2147483644 rack: null) is unavailable or invalid, will attempt rediscovery
2020-04-03 00:47:30 i.l.c.p.ConnectionWatchdog - Reconnecting, last destination was /192.168.140.130:6379
